### ISSUE TITLE
Docker Publish Action

### ISSUE THREAD

**Issue by dkfellows** [UoMResearchIT/Actions#12]
There's a pattern in https://github.com/UoMResearchIT/gene_prediction_tool/blob/dev/.github/workflows/build-test-push.yml that looks like it could be turned into an action.

Probably based on:
```
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push versioned
      run: |
        docker image tag ${{ env.CONTAINER_NAME }}:testing ghcr.io/${{ env.ORG_NAME }}/${{ env.CONTAINER_NAME }}:${{ github.event.inputs.version }}
        docker push ghcr.io/${{ env.ORG_NAME }}/${{ env.CONTAINER_NAME }}:${{ github.event.inputs.version }}
```
though the various parameters should be surfaced more neatly and defaulted usefully.

Note that the action will require the `packages: write` permission.
